# Generated by Django 6.0.1 on 2026-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpsession_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsession',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset', 'Reset'), ('customer', 'Customer Login')], max_length=10),
        ),
    ]
