# Generated by Django 6.0.1 on 2026-04-07 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bb_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('customer_gst', models.CharField(blank=True, default='', max_length=15)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('shop_address', models.TextField(blank=True, default='')),
                ('shop_gst', models.CharField(blank=True, default='', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_gst', models.BooleanField(default=False)),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('PhonePe', 'PhonePe'), ('GooglePay', 'GooglePay'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('Credit', 'Credit')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='business_billing.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bb_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('kg', 'KG'), ('gram', 'Gram'), ('litre', 'Litre'), ('ml', 'ML'), ('bag', 'Bag'), ('box', 'Box'), ('dozen', 'Dozen'), ('metre', 'Metre'), ('set', 'Set'), ('roll', 'Roll'), ('bundle', 'Bundle'), ('packet', 'Packet'), ('strip', 'Strip'), ('bottle', 'Bottle'), ('pair', 'Pair'), ('sachet', 'Sachet'), ('vial', 'Vial')], default='piece', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_qty_alert', models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('shop_type', models.CharField(blank=True, default='', max_length=30)),
                ('clothing_type', models.CharField(blank=True, default='', max_length=50)),
                ('clothing_size', models.CharField(blank=True, default='', max_length=20)),
                ('clothing_color', models.CharField(blank=True, default='', max_length=30)),
                ('clothing_gender', models.CharField(blank=True, default='', max_length=20)),
                ('hw_brand', models.CharField(blank=True, default='', max_length=50)),
                ('hw_material', models.CharField(blank=True, default='', max_length=50)),
                ('hw_model', models.CharField(blank=True, default='', max_length=100)),
                ('med_company', models.CharField(blank=True, default='', max_length=100)),
                ('med_schedule', models.CharField(blank=True, default='OTC', max_length=20)),
                ('med_expiry', models.CharField(blank=True, default='', max_length=7)),
                ('med_batch', models.CharField(blank=True, default='', max_length=50)),
                ('gold_purity', models.CharField(blank=True, default='', max_length=20)),
                ('metal_type', models.CharField(blank=True, default='', max_length=20)),
                ('gold_weight', models.CharField(blank=True, default='', max_length=20)),
                ('making_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bb_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='piece', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_stock_item', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business_billing.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='business_billing.product')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('extra_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.TextField()),
                ('shop_type', models.CharField(blank=True, choices=[('Kirana Store', 'Kirana Store'), ('Clothing', 'Clothing'), ('HardWare', 'HardWare'), ('Medical', 'Medical'), ('Gold and Silver', 'Gold and Silver'), ('Resturants', 'Resturants'), ('Genral Store', 'Genral Store'), ('Others', 'Others')], default='', max_length=30)),
                ('timings', models.CharField(blank=True, default='', max_length=100)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Profile',
                'verbose_name_plural': 'Shop Profiles',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('ENTRY', 'Stock Entry'), ('DEDUCTION', 'Sale Deduction'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=15)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='business_billing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='business_billing.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bb_stock_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
