# Generated by Django 6.0.1 on 2026-04-10 11:30

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0002_enable_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='customer_user_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'mobile'], name='customer_user_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='customer_name_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-created_at'], name='invoice_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='invoice_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'payment'], name='invoice_user_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'customer_mobile'], name='invoice_cust_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'is_gst', '-created_at'], name='invoice_gst_report_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('balance__gt', 0)), fields=['user', 'balance'], name='invoice_balance_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['customer_name'], name='invoice_custname_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoiceitem_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(condition=models.Q(('is_stock_item', True)), fields=['product'], name='invoiceitem_product_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'is_active'], name='product_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['user', 'category'], name='product_user_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['user', 'qty', 'min_qty_alert'], name='product_low_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('med_expiry__gt', '')), fields=['user', 'med_expiry'], name='product_med_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='shopprofile',
            index=models.Index(fields=['user', 'gst_enabled'], name='shopprofile_user_gst_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', '-created_at'], name='stocktx_product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['user', '-created_at'], name='stocktx_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='product_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='product_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='product_purchase_price_non_negative'),
        ),
    ]
