# Generated by Django 6.0.1 on 2026-04-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0004_customer_deleted_at_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessevent',
            name='bbevent_user_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessevent',
            name='bbevent_lookup_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='is_deleted',
        ),
        migrations.DeleteModel(
            name='BusinessEvent',
        ),
    ]
