# Generated by Django 6.0.1 on 2026-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0005_remove_businessevent_bbevent_user_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopscanner',
            name='scanner_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
