# Generated by Django 6.0.1 on 2026-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0006_alter_shopscanner_scanner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
