# Generated by Django 6.0 on 2026-05-14 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0007_alter_shopprofile_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_inclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_invoice',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(default='intra', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
