# Generated by Django 6.0.1 on 2026-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0009_gstpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='piece', max_length=20),
        ),
    ]
