# Generated by Django 6.0.1 on 2026-05-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0011_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
