# Generated by Django 6.0.1 on 2026-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0012_delete_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
