# Generated by Django 6.0.1 on 2026-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0016_userdevicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shop_mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shop_owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
