# Generated by Django 6.0.1 on 2026-06-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0017_invoice_shop_mobile_invoice_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
