# Generated by Django 6.0.1 on 2026-06-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0018_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
