# Generated by Django 6.0.1 on 2026-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0019_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='amount_paid_at_pickup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(blank=True, default='razorpay', max_length=50),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='payment_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
