# Generated by Django 6.0.1 on 2026-06-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0020_customerorder_amount_paid_at_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_customers', to='business_billing.shopscanner')),
            ],
            options={
                'verbose_name': 'Shop Customer',
                'unique_together': {('scanner', 'mobile_number')},
            },
        ),
    ]
