# Generated by Django 6.0.1 on 2026-07-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0025_invoice_public_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
