# Generated by Django 6.0.1 on 2026-07-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0026_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
