# Generated by Django 6.0.1 on 2026-07-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_billing', '0027_invoiceitem_description'),
    ]

    operations = [
    ]
