# Generated by Django 6.0.1 on 2026-05-28 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('business', 'Business Billing'), ('home-expense', 'Home Expenses'), ('construction', 'Construction'), ('custom', 'Custom')], max_length=30)),
                ('plan_key', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.CharField(choices=[('1 Month', '1 Month'), ('6 Months', '6 Months'), ('1 Year', '1 Year'), ('FREE_TRIAL', 'Free Trial')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
